### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by roidy** [enen92/screensaver.kaster#23]
Getting unicode errors and no images displayed. Kodi 19 latest kaster version.

```
2020-12-22 13:55:34.070 T:19609   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnicodeDecodeError'>
                                                   Error Contents: 'ascii' codec can't decode byte 0xc3 in position 167392: ordinal not in range(128)
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/screensaver.kaster/resources/lib/screensaver.py", line 61, in onInit
                                                       self.get_images()
                                                     File "/storage/.kodi/addons/screensaver.kaster/resources/lib/screensaver.py", line 120, in get_images
                                                       images = f.read()
                                                     File "/usr/lib/python3.8/encodings/ascii.py", line 26, in decode
                                                   UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 167392: ordinal not in range(128)
                                                   -->End of Python script error report<--
```

**Comment by roidy** [comment]
Fixed with pull request https://github.com/enen92/screensaver.kaster/pull/24
